# Generated by Django 3.1.3 on 2020-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='items',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
