# Generated by Django 3.1.3 on 2020-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20201124_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
